export const drivers = [
  {
    name: "Adams Martin",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Beidac Milan",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Blood Jason",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Bowden Dean",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Byrne Derek",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Carney David",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Cobey John",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Cogan Eanna",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Collins Martin",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Cummins Gerard",
    minHours: 35,
    maxHours: 39,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Devaney Declan",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Doyle Terrence",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Dzilic Miralem",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Foley Damian",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Heffernan Patrick",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Keegan Simon",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Kelly Mark",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Loftus David",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Long Rory",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "McCarthy Gerard",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "McCarthy Patrick",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "McNulty Gareth",
    minHours: 35,
    maxHours: 39,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Molloy David",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Monks Christopher",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: true,
    STA: false,
  },
  {
    name: "Murgui Adrian",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Nagy Otto",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Nagy Reimond",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Nolan Thomas",
    minHours: 35,
    maxHours: 39,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Norton Dylan",
    minHours: 16,
    maxHours: 18,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Nunes Alvoro",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "O,Brian William",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Pakenham John",
    minHours: 35,
    maxHours: 39,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Paul Naise",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Petronelli Mattia",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Pheelan Keeth",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Poulose Delmon",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Rowan Ian",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Tantin Ludovic",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Teague James",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Tynan John",
    minHours: 16,
    maxHours: 18,
    holidays: false,
    LTA: false,
    STA: false,
  },
  {
    name: "Zamfirou Victor",
    minHours: 30,
    maxHours: 35,
    holidays: false,
    LTA: false,
    STA: false,
  },
];
